"""нотификатион релатионшип

Revision ID: 0916e7cf3674
Revises: dae8554ce293
Create Date: 2026-05-22 11:21:21.409060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0916e7cf3674'
down_revision = 'dae8554ce293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_frozen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_frozen', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
