"""много чего

Revision ID: 0fcc7ec1b655
Revises: 0916e7cf3674
Create Date: 2026-05-24 14:18:00.032935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fcc7ec1b655'
down_revision = '0916e7cf3674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discuss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deny_reason', sa.String(), nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deny_reason', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('categories', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('thumbnail', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('images_names', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('video_link', sa.String(), nullable=True))
        batch_op.drop_column('image_name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('level')
        batch_op.drop_column('exp')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('video_link')
        batch_op.drop_column('images_names')
        batch_op.drop_column('thumbnail')
        batch_op.drop_column('categories')
        batch_op.drop_column('deny_reason')

    with op.batch_alter_table('discuss', schema=None) as batch_op:
        batch_op.drop_column('deny_reason')

    # ### end Alembic commands ###
