"""discsuesesee

Revision ID: 159eee2ab00e
Revises: 3ed151825d78
Create Date: 2026-03-10 13:40:12.817302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159eee2ab00e'
down_revision = '3ed151825d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_discuss', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('id_discuss')

    # ### end Alembic commands ###
