"""Initial migration

Revision ID: 16d23719c6e5
Revises: 
Create Date: 2026-04-09 16:55:27.206762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d23719c6e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    with op.batch_alter_table('discuss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('discuss', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.create_table('reply',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_author', sa.INTEGER(), nullable=True),
    sa.Column('id_discuss', sa.INTEGER(), nullable=True),
    sa.Column('id_comment', sa.INTEGER(), nullable=True),
    sa.Column('reply', sa.TEXT(), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
