"""Уведомления

Revision ID: 3861794be247
Revises: 9884ef686bd2
Create Date: 2026-03-01 14:42:21.133617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '3861794be247'
down_revision = '9884ef686bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notices')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notices', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
