"""фигня какая то

Revision ID: 3b1821bafd67
Revises: 0fcc7ec1b655
Create Date: 2026-05-24 14:19:13.716152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '3b1821bafd67'
down_revision = '0fcc7ec1b655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sqlite.JSON(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
