"""discuss

Revision ID: 3ed151825d78
Revises: 
Create Date: 2026-03-10 13:33:27.118713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed151825d78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dislikes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_discuss', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_dislikes_discuss', 'discuss', ['id_discuss'], ['id'])

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_discuss', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_likes_discuss', 'discuss', ['id_discuss'], ['id'])

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discuss_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notification_discuss', 'discuss', ['discuss_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notification_discuss', type_='foreignkey')
        batch_op.drop_column('discuss_id')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_likes_discuss', type_='foreignkey')
        batch_op.drop_column('id_discuss')

    with op.batch_alter_table('dislikes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_dislikes_discuss', type_='foreignkey')
        batch_op.drop_column('id_discuss')

    # ### end Alembic commands ###
