"""add named constraints

Revision ID: 6a675e9837f9
Revises: 159eee2ab00e
Create Date: 2026-03-11 17:07:15.939120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a675e9837f9'
down_revision = '159eee2ab00e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dislikes', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_dislikes_author_post', ['id_author', 'id_post'])

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_likes_author_post_discuss', ['id_author', 'id_post', 'id_discuss'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_likes_author_post_discuss', type_='unique')

    with op.batch_alter_table('dislikes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_dislikes_author_post', type_='unique')

    # ### end Alembic commands ###
