"""init

Revision ID: bd052193394b
Revises: 
Create Date: 2026-03-26 18:55:18.485713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'bd052193394b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.JSON(), nullable=True))
        batch_op.drop_column('comments')
        batch_op.drop_column('categories')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('comments', sa.INTEGER(), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
