"""кланы и друзья

Revision ID: cbd5b0b53170
Revises: 3b1821bafd67
Create Date: 2026-05-24 15:50:36.577385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd5b0b53170'
down_revision = '3b1821bafd67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clan', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('friends', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('friends')
        batch_op.drop_column('clan')

    # ### end Alembic commands ###
