"""Подписчики и миграции

Revision ID: dae8554ce293
Revises: 16d23719c6e5
Create Date: 2026-04-11 12:39:22.800429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae8554ce293'
down_revision = '16d23719c6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscribers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('banned_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('permanent_ban', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ban_reason', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ban_reason')
        batch_op.drop_column('permanent_ban')
        batch_op.drop_column('banned_until')
        batch_op.drop_column('subscribers')

    # ### end Alembic commands ###
